src/schema/index.js, src/sync/index.js, src/sync/models/centralizedOracle.js, src/sync/models/decentralizedOracle.js, src/sync/models/finalResultSet.js, src/sync/models/oracleResultSet.js, src/sync/models/topic.js, src/sync/models/vote.js
This will be large pr, 1 issue per commit for better track
1. fix #14: add resultSetEndBlock to oracle
2. fix #15: add resultSetterAddress to oracle
3. fix #16: add txid to topic/oracle/vote
4. fix #17: add consensusThreshold to oracle
=> add all missing fields from smart contract

src/sync/index.js
=> Translate catch

package-lock.json, package.json, src/config.js, src/sync/index.js
separate this fix into two commits. 
1: refactor all func to async/await to better handle error
2: batch rpc request and ensure requests r fired batch after batch
=> fix #43, #44, #46

package.json, src/db/nedb.js, src/schema/index.js, src/schema/resolvers.js, src/sync/index.js, src/utils/logger.js, src/utils/utils.js
related: https://github.com/bodhiproject/bodhi-ui/pull/127
update UI build files after ^ gets merged.
=> Blocktime sync info

main.js
Add copy paste short cut for the electron app and provide command+r to refresh.
=> add copy/paste and refresh short cut

src/schema/resolvers.js, src/sync/index.js
merge this one before: https://github.com/bodhiproject/bodhi-ui/pull/279
=> Fix logic for adding qtum balances

main.js
Overrides Electron to open external links (qtum explorer) in external browser.
=> Add logic to open urls in external browser

package.json, src/index.js, src/schema/resolvers.js, src/sync/index.js
=> use getpeerinfo for sync percent estimation

main.js, src/constants.js, src/index.js
Added Electron error dialog when trying to start up qtumd and kill server/app after closing dialog.
=> 120 elec error dialog

package.json
Changed some config for windows installer to display normal windows installer type.
=> 193 windows elec install

package-lock.json, package.json, src/api/blockchain.js, src/api/wallet.js, src/route/api.js, src/schema/index.js, src/schema/resolvers.js, src/sync/update_tx.js, src/test/api/blockchain.js, yarn.lock
**Update qtum 0.14.16 when this is merged in**
=> 137 send to address change address

main.js, package-lock.json, package.json, src/localization/i18n.js, src/localization/locale.json, yarn.lock
Tried a couple of libs, but nothing worked well. Most node libs are piggybacked on Express.
Decided to just create a simple localization util class.
=> Electron Localization

main.js, package-lock.json, package.json, src/localization/i18n.js, src/utils/utils.js
Get OS locale to start with correct lang in electron prod version.
=> 215 env prod

package.json, src/config/config.js, src/index.js, src/test/route/api.js, src/utils/logger.js
=> add tests for api

src/db/migrations/migrateTx.js, src/db/nedb.js, src/utils/utils.js
1. append `c0_d0/nedb/transactions.db` and `c0_d1/nedb/transactions.db` to `local/nedb/transactions.db`
2. rename `c0_d0/nedb/transactions.db` to `c0_d0/nedb/transactions.db.old`, `c0_d1/nedb/transactions.db` to `c0_d1/nedb/transactions.db.old` to avoid duplicated migration
3. change dev datadir to include version too.
=> transaction db migration

src/db/migrations/migrateTx.js, src/db/nedb.js, src/utils/utils.js
Signed-off-by: frankobe <mua08p@gmail.com>
=> fix typo err.msg -> err.message

package.json, src/sync/index.js
https://github.com/bodhiproject/bodhi-graphql/issues/249
=> adjust sync order to fix missing topicaddress

main.js, src/localization/locale.json
Added `About` dialog in electron menu that shows version code. Good for debugging when users have issues.
=> 266 about dialog

main.js, package-lock.json, package.json, src/localization/locale.json, yarn.lock
=> 282 check version

.gitmodules, main.js, src/localization/locale.json, src/utils/index.js
Depends on https://github.com/bodhiproject/bodhi-server/pull/50
**Update submodule hash after ^ merged**
=> Qtum path config
